### ISSUE TITLE
fix: cannot resolve meta pub dependecy

### ISSUE THREAD

**Issue by FluffyDiscord** [Gambley1/flutter-instagram-offline-first-clone#115]
**Description**

Trying to run pub get on freshly pulled project throws error

```
../sdk/flutter/bin/flutter --no-color pub get
Resolving dependencies...
Note: meta is pinned to version 1.12.0 by flutter_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of flutter_test from sdk depends on meta 1.12.0 and every version of insta_blocks from path depends on meta >=1.10.0 <1.12.0, flutter_test from sdk is incompatible with insta_blocks from path.
So, because flutter_instagram_offline_first_clone depends on both insta_blocks from path and flutter_test from sdk, version solving failed.
Process finished with exit code 1
```

**Steps To Reproduce**

1. Clone repository
2. `flutter pub get`
3. See error

**Expected Behavior**

Pub get without any issue.

**Screenshots**

nope

**Additional Context**

**Comment by Gambley1** [comment]
It seems that Flutter new version Sdk has pinned meta version to 1.12.0. However, I didn't update the Flutter Sdk to the latest version in the project. Therefore, you see dependencies incompatible message.

You can try to change the constraints for the meta in insta_blocks package from ">=1.10.0 <1.12.0" to ">=1.10.0 <=1.12.0".

Hope it helps!

**Comment by Gambley1** [comment]
This only happens because you have newer Flutter sdk version that this project for now. I will update it later. So it is not the issue of the project itself.

The only sign that something is broken on my side and in the project, is if the recent flutter_instagram_offline_first_clone github action in the Actions tab was not successful. Therefore, if you see it, it you don't see any unsuccessful jobs it must be something on your side. Take it into account, so in future you don't confuse yourself.
